#PBS -P myrtaceae
#PBS -N interproscan
#PBS -l select=1:ncpus=4:mem=15gb
#PBS -l walltime=5:00:00
#PBS -M peri.tobias@sydney.edu.au
#PBS -m abe

#Parameters
wdir=/scratch/myrtaceae
outdir=$wdir/2.results

# Load modules
module load interproscan/5.39-77.0
module load java/jdk-11.0.5

# Working directory
cd $PBS_O_WORKDIR

#Run interproscan script to obtain the domain strucutres of predicted 'genes' from braker2. Ensure that the '*' stop codon is removed from the fasta sequence before running.

#interproscan.sh -t p -appl COILS,Pfam,SUPERFAMILY -i $wdir/1.data/E_grandis.NLR.aa.fasta -f tsv,gff3 -d $outdir/
interproscan.sh -t p -appl Pfam,COILS,Gene3D -i $wdir/1.data/$input_fasta -f tsv,gff3 -d $outdir/


module unload interproscan/5.39-77.0
module unload java/jdk-11.0.5
